### ISSUE TITLE
Add markdown/link checker integration to repo

### ISSUE THREAD

**Issue by booyaa** [rust-community/content-o-tron#10]
**Blocked:** Need to check wirth main team it's okay to add content-o-tron collaborates to the Rust Community org. This is a permissions issue, we need a member of the Community org to add Travis.

### Description

To help spot broken links when writing any project documentation (written in markdown).

Tool to use (alternatives are welcome): https://github.com/dkhamsing/awesome_bot

Validation should occur during pull request. Instructions on how to do this can be found [here](https://github.com/dkhamsing/awesome_bot#travis-ci)

### Estimation

3.5 hours

### Actions required if claiming this task

- Mentoring can be provided, just ask.
- Please add comment if you are claiming this issue so we can assign it to you.

### Admin use only (please leave as-is do not delete from issue)

Collaborators: @adityac8
Mentor: @booyaa

**Comment by adityac8** [comment]
Hey, I would like to work on this one 😃

**Comment by booyaa** [comment]
It's yours thank you!

**Comment by booyaa** [comment]
It looks like the markdown linter vanished after the repo was transferred to rust-community org. Let me update the issue, to provide more details.

**Comment by booyaa** [comment]
Updated the issue, let me know if you have any more questions!

**Comment by adityac8** [comment]
User from https://github.com/rust-community can add Travis or might need permission.

**Comment by adityac8** [comment]
Hey @booyaa We can remove `blocked` now. I'm adding Travis.

**Comment by adityac8** [comment]
I think we can close this now 😎

**Comment by booyaa** [comment]
Cool thanks!
