### ISSUE TITLE
Improving the blog post template

### ISSUE THREAD

**Issue by booyaa** [rust-community/content-o-tron#18]
Collaborators: @aariops 
___
I transferred the contents from a google doc. I remove some Mozilla internal process and the example blog post. I replace those with Rust-centric posts that appeared in the Mozilla Hacks site.

Can the template be improved upon? Is it easy enough to follow?

Template can be found in [/guides/blog_post_template.md](https://github.com/rust-community/content-o-tron/blob/master/guides/blog_post_template.md)
___
Mentoring can be provided, just ask.
Please add comment if you are claiming this issue so we can assign it to you.

**Comment by aariops** [comment]
@booyaa hey! where is the template? I can try an help.

**Comment by booyaa** [comment]
@aariops hi thanks! here you go! https://github.com/rust-community/content-o-tron/blob/master/guides/blog_post_template.md I'll update the issue too.
