### ISSUE TITLE
Rework the roadmap

### ISSUE THREAD

**Issue by booyaa** [rust-community/content-o-tron#19]
We did a soft launch by running a shadow campaign of the blog posts that came out of the first ever Rust All Hands (#6). Doing the soft launch cause myself to wonder if the roadmap is still relevant.

I think the road map should be revised to reflect the following goals:

- Retrospective on the Rust All Hands campaign (soft launch)
- Planning how the team continues post Mozilla Global Sprint 2018
- Review the campaign process (including possibilities of automation for v1.0.0)
- Internal automation tools (issue harvester, automated peer review assignment, etc)

Please share any thoughts (via comments below), I'm also happy to discuss via chat to brainstorm further.

**Comment by adityac8** [comment]
I think the Roadmap was updated in #59. If it is fine, we should close this now. 🚗

**Comment by booyaa** [comment]
New roadmap #55
