### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by booyaa** [rust-community/content-o-tron#2]
# Roadmap

### Milestone: Define the process

> We identify the steps required to start a blogging campaign. The type of help we'll for each step.

### Milestone: Recruit contributors and/or sponsorship

> We begin to advertise and recruit (based on recommendations) additional contributors. We also identify any funding or sponsorship that can help pay for any specialists we may need.

### Milestone: Recruit users aka the soft launch

> We solicit seed posts for our first campaign, these are users who have previously contributed on other Rust blogging campaigns.

### Milestone: Run our first campaign

> We open blog post pledges to the public. We follow the process and amend it if necessary.

### Milestone: Refactor the process 

> We do a retrospective of the process, what went well, what didn't go well. We improve the process and share our findings with stake holders, contributors and users.

**Comment by havi** [comment]
I am really interested/self-interested in following along, helping out with editorial review, and helping promote this 'experiment' in a variety of channels....

**Comment by booyaa** [comment]
replaced by #55
