### ISSUE TITLE
Link to the "Running a campaign" guide in the "new campaign" issue template

### ISSUE THREAD

**Issue by booyaa** [rust-community/content-o-tron#41]
Collaborators:
____

The "new campaign" issue template to be edited can be found here: https://github.com/rust-community/content-o-tron/blob/master/ISSUE_TEMPLATE/new_campaign.md

The "Running a new campaign" guide can be found here: https://github.com/rust-community/content-o-tron/blob/master/guides/running_a_campaign.md

Mentor:
___
Mentoring can be provided, just ask.
Please add comment if you are claiming this issue so we can assign it to you.

**Comment by adityac8** [comment]
I'm on it!
