### ISSUE TITLE
Add all MozSprint labelled issues to tracking issue

### ISSUE THREAD

**Issue by booyaa** [rust-community/content-o-tron#56]
### Description

- [x] Link all [`mozsprint`](https://github.com/rust-community/content-o-tron/issues?q=is%3Aopen+is%3Aissue+label%3Amozsprint) labelled issues to the related tracking issue: #8 
- [x] Remove `mozprint` label from these issues (except the tracking issue).

### Estimation

0.5m hours

### Actions required if claiming this task

- Mentoring can be provided, just ask.
- Please add comment if you are claiming this issue so we can assign it to you.

### Admin use only (please leave as-is do not delete from issue)

Collaborators: (add here if not a current maintainer otherwise assign)
Mentor: (insert name or delete if not required)

**Comment by adityac8** [comment]
I'm on it! Should I link the closed as well as open issues here?

**Comment by adityac8** [comment]
I have added the link to closed and open issues in the tracking issue 😸

**Comment by booyaa** [comment]
Turned steps into checkbox tasks. Looks good, go ahead and remove the `mozsprint` label please.

Also we'll close the sprint issue too because the event has finished. It doesn't need to `blocked`.

**Comment by adityac8** [comment]
Done! :+1:

**Comment by booyaa** [comment]
Awesome thanks!
