### ISSUE TITLE
Blogging assistance: Rust and OpenFaaS

### ISSUE THREAD

**Issue by booyaa** [rust-community/content-o-tron#68]
# Welcome!

**Tip:** Writing can be daunting, if you're stuck writing a new blog post, please see our [blog post template](/guides/blog_post_template.md).

Otherwise please fill out the form below to initiate a request for assistance.

### 1. Give your issue a title

The suggested format is `Blogging assistance: title of your blog post`.

### 2. What type of help do you need (check one or more items)

- [ ] editing of blog post
- [ ] technical review of blog post
- [x] general advice/feedback on the blog post (mentoring)
- [ ] other (please specify below)

I have two questions, does this have enough interest for Rust readers? And do you understand enough about Serverless Functions from what I've written about in the blog post. Any other feedback is appreciated!

### 3. Provide a link to your blog post draft

https://github.com/booyaa/booyaa.github.io/pull/7

#### Adding your draft to the Content-o-Tron repository

If this is part of an existing blogging campaign initiated by Content-o-Tron :robot: then you can place your draft (via pull request) in the appropriate campaigns folder (`/campaigns/name_of_campaign`) of this repo.

Alternatively if this is not part of a blogging campaign then you can create a draft in the campaigns ad-hoc folder (`/campaigns/ad-hoc`).

### 4. Describe the nature of the problem

Please provide as much detail as you can.

## Next steps

- The team will review the issue and tag it based on what you need.
- A person with the appropriate skills will be assigned and communicate via this issue.

---

### Add this issue to tracking issue if part of campaign

You can ignore this section, but do not delete. 

### Automation link

Update `README.md` if you the title or labels.

```text
https://github.com/rust-community/content-o-tron/issues/new?template=help_wanted.md&title=Help+with+blog+post+:+TITLE+OF+POST&labels=help-triage
```

**Comment by aidanhs** [comment]
I'm confused - is this an issue to review the youtube video?

**Comment by booyaa** [comment]
Sorry @aidanhs I botched the PR and then forgot to update. Here's the finished blog post: https://booyaa.wtf/2018/run-rust-in-openfaas/
