### ISSUE TITLE
Tracking: Mozilla's Global Sprint 2018 Attendees and Tasks

### ISSUE THREAD

**Issue by booyaa** [rust-community/content-o-tron#8]
## Welcome!

The project will be part of [Mozilla's Global Sprint](http://mzl.la/global-sprint/) May 10-11, 2017! 

![Global Sprint](https://user-images.githubusercontent.com/617994/37716586-3b0397a0-2cf5-11e8-8c6f-bad01f67f50e.jpg)

We'll be attending the event hosted at [Mozilla London](https://ti.to/Mozilla/global-sprint-london18) 🇬🇧. If you can't attend in person, you can still participate [virtually](https://ti.to/Mozilla/global-sprint-virtual18).

Finally if you are attending in either form, please add a comment here so we can plan the workload.

## Updates

- Q & A session (10mins) at the Rust Content team meeting on Tuesday 8th. We meet on the IRC, the issue has a link to access IRC if you've never used it before. https://github.com/rust-community/content-team/issues/28
- We've created a [milestone](https://github.com/rust-community/content-o-tron/milestone/1) specifically for this sprint, these are the issues we'd like to close before the end of the sprint.
- We'll be tracking our progress during the sprint via [this](https://github.com/rust-community/content-o-tron/projects/1) [Kanban](https://en.wikipedia.org/wiki/Kanban) board.
- We've got a gitter room! You can join us by clicking on this button! [![Gitter chat](https://badges.gitter.im/gitterHQ/gitter.png)](https://gitter.im/content-o-tron/Lobby)

**Comment by skade** [comment]
Hi, I'll be around a bit!

**Comment by adityac8** [comment]
I'm contributing here Yay!

**Comment by aariops** [comment]
Hey! I can help with the blog template. :smile:

**Comment by o0Ignition0o** [comment]
Hey there, I'm around too, just started Blogception on https://blog.jeremylempereur.com to help rustaceans set up their own GitHub pages blog ! :)

**Comment by booyaa** [comment]
Adding @poshaughnessy @fourplusone

**Comment by adityac8** [comment]
Here are all the issues we worked upon during the mozsprint:
#10
#11
#12
#15
#17
#18
#19
#21
#22
#23
#24
#31
#35
#41
#42
#45
#46
#51
#53
#54

**Comment by adityac8** [comment]
Discussed on #56 Closing this issue.
